export const holdings = [
  {
    id: 1,
    name: "Mckesson",
    symbol: "MCK",
    currentPrice: 0,
    investment: 3333,
    currentValue: 0,
    dayChange: 0,
    change: 0,
    stopLossPrice: 250,
    qty: 25,
    currency: "USD",
  },
  {
    id: 2,
    name: "Lockhead",
    symbol: "LMT",
    currentPrice: 0,
    investment: 4487,
    currentValue: 0,
    dayChange: 0,
    change: 0,
    stopLossPrice: 440,
    qty: 10,
    currency: "USD",
  },
  {
    id: 3,
    name: "Google",
    symbol: "GOOGL",
    currentPrice: 0,
    investment: 3451,
    currentValue: 0,
    dayChange: 0,
    change: 0,
    stopLossPrice: 66,
    qty: 60,
    currency: "USD",
  },
  {
    id: 4,
    name: "global water",
    symbol: "CWW.TO",
    currentPrice: 0,
    investment: 3647,
    currentValue: 0,
    dayChange: 0,
    change: 0,
    stopLossPrice: 40,
    qty: 125,
    currency: "CAD",
  },
  {
    id: 5,
    name: "carbon",
    symbol: "KRBN",
    currentPrice: 0,
    investment: 3235,
    currentValue: 0,
    dayChange: 0,
    change: 0,
    stopLossPrice: 34,
    qty: 100,
    currency: "USD",
  },
  {
    id: 6,
    name: "Yen short",
    symbol: "YCS",
    currentPrice: 0,
    investment: 2100,
    currentValue: 0,
    dayChange: 0,
    change: 0,
    stopLossPrice: 48,
    qty: 48,
    currency: "USD",
  },
];
