export const holdings = [
  {
    id: 1,
    name: "Mckesson",
    symbol: "MCK",
    currentPrice: 0,
    investment: 3370,
    currentValue: 0,
    dayChange: 0,
    change: 0,
    stopLossPrice: 250,
    qty: 25,
    currency: "USD",
    lastUpdate: "",
  },
  {
    id: 3,
    name: "Google",
    symbol: "GOOGL",
    currentPrice: 0,
    investment: 3531,
    currentValue: 0,
    dayChange: 0,
    change: 0,
    stopLossPrice: 66,
    qty: 60,
    currency: "USD",
    lastUpdate: "",
  },
  {
    id: 4,
    name: "global water",
    symbol: "CWW.TO",
    currentPrice: 0,
    investment: 3647,
    currentValue: 0,
    dayChange: 0,
    change: 0,
    stopLossPrice: 40,
    qty: 125,
    currency: "CAD",
    lastUpdate: "",
  },
  {
    id: 5,
    name: "carbon",
    symbol: "KRBN",
    currentPrice: 0,
    investment: 3235,
    currentValue: 0,
    dayChange: 0,
    change: 0,
    stopLossPrice: 34,
    qty: 100,
    currency: "USD",
    lastUpdate: "",
  },
  {
    id: 6,
    name: "Yen short",
    symbol: "YCS",
    currentPrice: 0,
    investment: 2100,
    currentValue: 0,
    dayChange: 0,
    change: 0,
    stopLossPrice: 48,
    qty: 48,
    currency: "USD",
    lastUpdate: "",
  },
  {
    id: 7,
    name: "MICROSOFT",
    symbol: "MSFT",
    currentPrice: 0,
    investment: 3518,
    currentValue: 0,
    dayChange: 0,
    change: 0,
    stopLossPrice: 324,
    qty: 11,
    currency: "USD",
    lastUpdate: "",
  },
  {
    id: 7,
    name: "TSM",
    symbol: "TSM",
    currentPrice: 0,
    investment: 3228,
    currentValue: 0,
    dayChange: 0,
    change: 0,
    stopLossPrice: 97,
    qty: 30,
    currency: "USD",
    lastUpdate: "",
  }
];
