export const holdings = [
  {
    id: 1,
    name: "Mckesson",
    symbol: "MCK",
    currentPrice: 0,
    investment: 3333,
    currentValue: 0,
    dayChange: 0,
    change: 0,
    stopLossPrice: 250,
    qty: 25,
  },
  {
    id: 2,
    name: "Lockhead",
    symbol: "LMT",
    currentPrice: 0,
    investment: 4487,
    currentValue: 0,
    dayChange: 0,
    change: 0,
    stopLossPrice: 440,
    qty: 10,
  },
  {
    id: 3,
    name: "Google",
    symbol: "GOOGL",
    currentPrice: 0,
    investment: 3451,
    currentValue: 0,
    dayChange: 0,
    change: 0,
    stopLossPrice: 66,
    qty: 60,
  },
];
